Blogger\BlogBundle\Entity\Comment:
  type: entity
  repositoryClass: Blogger\BlogBundle\Repository\CommentRepository
  table: comment
  fields:
    id:
      type: integer
      length: null
      precision: 0
      scale: 0
      nullable: false
      unique: false
      id: true
      generator:
        strategy: IDENTITY
    user:
      type: string
      length: null
      precision: 0
      scale: 0
      nullable: false
      unique: false
    comment:
      type: text
      length: null
      precision: 0
      scale: 0
      nullable: false
      unique: false
    approved:
      type: boolean
      length: null
      precision: 0
      scale: 0
      nullable: false
      unique: false
    created:
      type: datetime
      length: null
      precision: 0
      scale: 0
      nullable: false
      unique: false
    updated:
      type: datetime
      length: null
      precision: 0
      scale: 0
      nullable: false
      unique: false
  manyToOne:
    blog:
      targetEntity: Blogger\BlogBundle\Entity\Blog
      cascade: {  }
      mappedBy: null
      inversedBy: comments
      joinColumns:
        blog_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks:
    preUpdate:
      - setUpdatedValue
